import React, { useState, useRef } from 'react';
import ReactQuill from 'react-quill-new';
import 'react-quill-new/dist/quill.snow.css';
import { supabase } from '../services/supabaseClient';
import { useToast } from './ToastContext';
import { Upload, Loader2, CheckCircle2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const CATEGORIES = ['GST', 'Virtual Office', 'Company Setup', 'Compliance', 'Expansion'];

export default function AdminBlogEditor() {
  const [title, setTitle] = useState('');
  const [category, setCategory] = useState(CATEGORIES[0]);
  const [excerpt, setExcerpt] = useState('');
  const [content, setContent] = useState('');
  const [imageUrl, setImageUrl] = useState('');
  
  const [isUploading, setIsUploading] = useState(false);
  const [isPublishing, setIsPublishing] = useState(false);
  
  const { addToast } = useToast();
  const fileInputRef = useRef(null);

  const handleImageUpload = async (e) => {
    const file = e.target.files[0];
    if (!file) return;

    setIsUploading(true);
    try {
      const fileExt = file.name.split('.').pop();
      const fileName = `${Date.now()}-${Math.random().toString(36).substring(7)}.${fileExt}`;
      const filePath = `images/${fileName}`;

      const { error: uploadError } = await supabase.storage
        .from('blog-images')
        .upload(filePath, file);

      if (uploadError) throw uploadError;

      const { data: { publicUrl } } = supabase.storage
        .from('blog-images')
        .getPublicUrl(filePath);

      setImageUrl(publicUrl);
      addToast('success', 'Image uploaded successfully!');
    } catch (error) {
      console.error('Error uploading image:', error);
      addToast('error', 'Failed to upload image');
    } finally {
      setIsUploading(false);
    }
  };

  const handlePublish = async () => {
    if (!title || !excerpt || !content || !imageUrl) {
      addToast('error', 'Please fill in all fields including the cover image.');
      return;
    }

    setIsPublishing(true);
    try {
      // Slug generation from title
      const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, '');

      const { error } = await supabase
        .from('blog_posts')
        .insert([
          {
            title,
            slug,
            category,
            excerpt,
            content,
            image_url: imageUrl,
            published: true,
            // 'created_at' is usually auto-generated by Supabase
          }
        ]);

      if (error) throw error;

      addToast('success', 'Blog post published successfully!');
      
      // Reset form
      setTitle('');
      setCategory(CATEGORIES[0]);
      setExcerpt('');
      setContent('');
      setImageUrl('');
      
    } catch (error) {
      console.error('Error publishing post:', error);
      addToast('error', 'Failed to publish post');
    } finally {
      setIsPublishing(false);
    }
  };

  const modules = {
    toolbar: [
      [{ 'header': [1, 2, 3, false] }],
      ['bold', 'italic', 'underline', 'strike'],
      [{ 'list': 'ordered'}, { 'list': 'bullet' }],
      ['link', 'image', 'clean']
    ],
  };

  return (
    <div className="fade-up-enter max-w-[1000px] pb-20">
      <div className="mb-7 flex justify-between items-start">
        <div>
          <h1 className="text-[20px] font-[800] text-[#111110]">Write a Blog</h1>
          <p className="text-[13px] text-[rgba(17,17,16,0.45)] mt-1">Create and publish a new article</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-[1fr_300px] gap-6">
        <div className="flex flex-col gap-6">
          <div className="bg-white rounded-[14px] border border-[rgba(17,17,16,0.08)] p-6 shadow-sm">
            <label className="block text-[13px] font-[600] text-[#111110] mb-2">Title</label>
            <input 
              type="text" 
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="Enter post title"
              className="w-full h-[44px] bg-[#F9F8F5] border border-[rgba(17,17,16,0.1)] rounded-[10px] px-3 text-[14px] outline-none focus:border-[#1B6B2F] focus:bg-white transition-colors"
            />
          </div>

          <div className="bg-white rounded-[14px] border border-[rgba(17,17,16,0.08)] p-6 shadow-sm">
            <label className="block text-[13px] font-[600] text-[#111110] mb-2">Content</label>
            <div className="h-[400px] pb-10">
              <ReactQuill 
                theme="snow" 
                value={content} 
                onChange={setContent} 
                modules={modules}
                style={{ height: '350px' }}
              />
            </div>
          </div>
        </div>

        <div className="flex flex-col gap-6">
          <div className="bg-white rounded-[14px] border border-[rgba(17,17,16,0.08)] p-6 shadow-sm sticky top-[32px]">
            <label className="block text-[13px] font-[600] text-[#111110] mb-2">Category</label>
            <select 
              value={category}
              onChange={(e) => setCategory(e.target.value)}
              className="w-full h-[44px] bg-[#F9F8F5] border border-[rgba(17,17,16,0.1)] rounded-[10px] px-3 text-[14px] outline-none focus:border-[#1B6B2F] focus:bg-white transition-colors"
            >
              {CATEGORIES.map(cat => <option key={cat} value={cat}>{cat}</option>)}
            </select>

            <label className="block text-[13px] font-[600] text-[#111110] mt-5 mb-2">Excerpt</label>
            <textarea 
              value={excerpt}
              onChange={(e) => setExcerpt(e.target.value)}
              placeholder="Short summary..."
              rows={3}
              className="w-full bg-[#F9F8F5] border border-[rgba(17,17,16,0.1)] rounded-[10px] p-3 text-[14px] outline-none focus:border-[#1B6B2F] focus:bg-white resize-none transition-colors"
            />

            <label className="block text-[13px] font-[600] text-[#111110] mt-5 mb-2">Cover Image</label>
            <div 
              onClick={() => fileInputRef.current?.click()}
              className="w-full h-[140px] rounded-[10px] border-2 border-dashed border-[rgba(17,17,16,0.15)] flex flex-col items-center justify-center cursor-pointer hover:border-[#1B6B2F] hover:bg-[#F9F8F5] transition-colors relative overflow-hidden"
            >
              {imageUrl ? (
                <img src={imageUrl} alt="Cover" className="w-full h-full object-cover" />
              ) : isUploading ? (
                <div className="flex flex-col items-center">
                  <Loader2 className="animate-spin text-[#1B6B2F] mb-2" size={24} />
                  <span className="text-[12px] text-[rgba(17,17,16,0.5)]">Uploading...</span>
                </div>
              ) : (
                <>
                  <Upload size={24} className="text-[rgba(17,17,16,0.3)] mb-2" />
                  <span className="text-[12px] text-[rgba(17,17,16,0.5)]">Click to upload</span>
                </>
              )}
            </div>
            <input 
              type="file" 
              ref={fileInputRef} 
              onChange={handleImageUpload} 
              accept="image/*" 
              className="hidden" 
            />

            <button 
              onClick={handlePublish}
              disabled={isPublishing || isUploading}
              className="w-full h-[44px] bg-[#1B6B2F] text-white rounded-[100px] font-[600] mt-8 flex items-center justify-center gap-2 hover:bg-[#145324] transition-colors disabled:opacity-50 disabled:hover:bg-[#1B6B2F]"
            >
              {isPublishing ? <Loader2 className="animate-spin" size={18} /> : <CheckCircle2 size={18} />}
              {isPublishing ? 'Publishing...' : 'Publish Post'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
